events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    #
    # JSON access log
    #
    log_format json_combined escape=json
    '{'
        '"timestamp":"$time_iso8601",'
        '"request_id":"$request_id",'
        '"remote_addr":"$remote_addr",'
        '"request_method":"$request_method",'
        '"request_uri":"$request_uri",'
        '"status":$status,'
        '"body_bytes_sent":$body_bytes_sent,'
        '"request_time":$request_time,'
        '"upstream_response_time":"$upstream_response_time",'
        '"host":"$host",'
        '"http_referer":"$http_referer",'
        '"http_user_agent":"$http_user_agent"'
    '}';

    #
    # Docker stdout / stderr
    #
    access_log /dev/stdout json_combined;
    error_log /dev/stderr warn;

    #
    # Django
    #
    upstream django {
        server django:8000;
    }

    server {
        listen 80;

        server_name _;

        #
        # Static
        #
        location /static/ {
            alias /static/;
        }

        #
        # Media
        #
        location /media/ {
            alias /media/;
        }

        #
        # WebSocket
        #
        location /ws/ {
            proxy_pass http://django;

            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header X-Request-ID $request_id;

            proxy_read_timeout 86400;
            proxy_send_timeout 86400;
        }

        #
        # HTTP
        #
        location / {
            proxy_pass http://django;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header X-Request-ID $request_id;

            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
    }
}
