# Generated by Django 4.0.1 on 2022-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='posts',
        ),
        migrations.AddField(
            model_name='tags',
            name='news',
            field=models.ManyToManyField(to='news.News'),
        ),
    ]
