# Generated by Django 4.0.1 on 2026-08-24 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('', ''), ('petr', 'Petrol'), ('dies', 'Diesel'), ('hyb', 'Hybrid'), ('elec', 'Electro')], default='No type', max_length=100)),
                ('engine_capacity', models.FloatField(default='No capacity')),
                ('drive', models.CharField(choices=[('', ''), ('fwd', 'Front-wheel drive'), ('rwd', 'Rear-wheel drive'), ('awd', 'Automatic 4WD'), ('4wd', 'Full-time 4WD')], default='No type', max_length=100)),
                ('gear_box', models.CharField(choices=[('', ''), ('auto', 'Automatic'), ('man', 'Manual')], default='No type', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('win', models.CharField(blank=True, max_length=17, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('phone_number', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('', ''), ('go', 'Auction going '), ('soon', 'Soon'), ('stop', 'Auction ended')], default='stop', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarMarkAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_mark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auction.auction')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarModelAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100, unique=True)),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodelsauction', to='auction.carmarkauction')),
            ],
        ),
        migrations.CreateModel(
            name='CarAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None)),
                ('favorites', models.ManyToManyField(related_name='favorite_carsauction', to=settings.AUTH_USER_MODEL)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carsauction', to='auction.carmarkauction')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carsauction', to='auction.carmodelauction')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bef_bid_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auction.carauction'),
        ),
        migrations.AddField(
            model_name='auction',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
