# Generated by Django 4.0.1 on 2026-09-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('', ''), ('go', 'Auction going'), ('soon', 'Soon'), ('stop', 'Auction ended')], default='stop', max_length=20),
        ),
    ]
