# Generated by Django 4.0.1 on 2022-03-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_auction_date_end_alter_auction_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
