# Generated by Django 4.0.1 on 2026-09-21 12:19

from django.db import migrations


def copy_auction_images(apps, schema_editor):
    Auction = apps.get_model('auction', 'Auction')
    AuctionImage = apps.get_model('auction', 'AuctionImage')
    for auction in Auction.objects.all():
        if auction.image:
            AuctionImage.objects.create(auction_id=auction.id, image=auction.image)


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auctionimage'),
    ]

    operations = [
        migrations.RunPython(copy_auction_images, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
    ]
