# Generated by Django 4.0.1 on 2022-03-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_auction_date_end_alter_auction_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='engine_capacity',
            field=models.FloatField(default='No capacity'),
        ),
    ]
