# Generated by Django 4.0.1 on 2022-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_auction_engine_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
