# Generated by Django 4.0.1 on 2026-09-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodelauction',
            name='car_mark',
        ),
        migrations.DeleteModel(
            name='CarAuction',
        ),
        migrations.DeleteModel(
            name='CarMarkAuction',
        ),
        migrations.DeleteModel(
            name='CarModelAuction',
        ),
    ]
