# Generated by Django 4.0.1 on 2026-09-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_remove_carmodelauction_car_mark_delete_carauction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auction',
            name='win',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
    ]
