# Generated by Django 4.0.1 on 2022-03-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('go', 'Auction in underway '), ('soon', 'Auction started soon'), ('stop', 'Auction ended')], default='stop', max_length=20),
        ),
    ]
