# Generated by Django 4.0.1 on 2022-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bef_bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
