# Generated by Django 4.0.1 on 2022-03-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_alter_bid_bef_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bef_bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, unique=True),
        ),
    ]
