# Generated by Django 4.0.1 on 2022-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_alter_bid_bef_bid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='price_usd',
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('go', 'Auction going '), ('soon', 'Soon'), ('stop', 'Auction ended')], default='stop', max_length=20),
        ),
    ]
