# Generated by Django 4.0.1 on 2022-03-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0015_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='auction',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
