# Generated by Django 4.0.1 on 2022-03-26 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0016_alter_winner_auction_alter_winner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='auction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
