# Generated by Django 4.0.1 on 2022-11-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_alter_winner_auction_alter_winner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='drive',
            field=models.CharField(choices=[('', ''), ('fwd', 'Front-wheel drive'), ('rwd', 'Rear-wheel drive'), ('awd', 'Automatic 4WD'), ('4wd', 'Full-time 4WD')], default='No type', max_length=100),
        ),
        migrations.AlterField(
            model_name='auction',
            name='engine_type',
            field=models.CharField(choices=[('', ''), ('petr', 'Petrol'), ('dies', 'Diesel'), ('hyb', 'Hybrid'), ('elec', 'Electro')], default='No type', max_length=100),
        ),
        migrations.AlterField(
            model_name='auction',
            name='gear_box',
            field=models.CharField(choices=[('', ''), ('auto', 'Automatic'), ('man', 'Manual')], default='No type', max_length=100),
        ),
    ]
