# Generated by Django 4.0.1 on 2022-12-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_alter_auction_drive_alter_auction_engine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('', ''), ('go', 'Auction going '), ('soon', 'Soon'), ('stop', 'Auction ended')], default='stop', max_length=20),
        ),
    ]
