input {
    beats {
        port => 5044
    }
}

filter {
    # Защита от повторного попадания логов
    if [container][image][name] =~ /logstash/ {
        drop {}
    }

    if [container][image][name] =~ /filebeat/ {
        drop {}
    }

    # Django / Nginx JSON logs
    json {
        source => "message"
        skip_on_invalid_json => true
    }

    # Django JSON logs
    if [asctime] {
        date {
            match => [ "asctime", "YYYY-MM-dd HH:mm:ss,SSS" ]
            target => "@timestamp"
        }

        mutate {
            rename => {
                "levelname" => "level"
                "name" => "logger"
            }
        }
    }

    # Nginx JSON logs
    if [timestamp] {
        date {
            match => [ "timestamp", "ISO8601" ]
            target => "@timestamp"
        }

        mutate {
            remove_field => ["timestamp"]
        }
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "carwager-logs-%{+YYYY.MM.dd}"
    }
}
