"""
Django settings for general project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-x47s268xj7f(5)-otz^_4+e*&bto6r6g_)nop5p$j4^ayf^aia"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://0.0.0.0:8080",
    "https://carwager.herokuapp.com",
    "http://127.0.0.1",
]
# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "crispy_forms",
    "crispy_bootstrap5",
    "django_rq",
    "showbill",
    "news",
    "general",
    "auction",
    "chat",  # новое приложение для чата
]

MIDDLEWARE = [
    "general.middleware.RequestIDMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv("REDIS_HOST", "redis"), 6379)],
        },
    },
}

ROOT_URLCONF = "general.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "general.wsgi.application"
ASGI_APPLICATION = "general.asgi.application"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_NAME", "carwager"),
        "USER": os.getenv("POSTGRES_USER", "carwager"),
        "PASSWORD": os.getenv("POSTGRES_PASS", "carwager"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": 5432,
    }
}

# REST framework
# https://www.django-rest-framework.org/tutorial/quickstart/
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "PAGE_SIZE": 10,
}


# Redis server
RQ_QUEUES = {
    "default": {
        "HOST": os.getenv("REDIS_HOST", "localhost"),
        "PORT": 6379,
        "DB": 0,
        "DEFAULT_TIMEOUT": 360,
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Static files (CSS, JavaScript, Images)
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (Uploads)
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Cache (Redis via django-redis)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.getenv('REDIS_HOST', 'redis')}:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "logout"

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#         },
#     },
#     "root": {
#         "handlers": ["console"],
#         "level": "INFO",
#     },
#     "scrapy.core.scraper": {
#         "handlers": [],
#         "level": "ERROR",
#     },
#     "django.db.backends": {
#         "handlers": ["console"],
#         "level": "ERROR",
#     },
# }
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    # ============================================================
    # FILTERS
    # ============================================================

    "filters": {
        "context": {
            "()": "general.logging.ContextFilter",
        },
    },

    # ============================================================
    # FORMATTERS
    # ============================================================

    "formatters": {
        "json": {
            "()": "pythonjsonlogger.json.JsonFormatter",
            "format": (
                "%(asctime)s "
                "%(levelname)s "
                "%(name)s "
                "%(message)s "
                "%(service)s "
                "%(environment)s"
                "%(request_id)s"
            ),
        },
    },

    # ============================================================
    # HANDLERS
    # ============================================================

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "json",
            "filters": ["context"],
        },
    },

    # ============================================================
    # LOGGERS
    # ============================================================

    "loggers": {

        # --------------------------------------------------------
        # Django
        # --------------------------------------------------------

        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # --------------------------------------------------------
        # Django HTTP requests
        # --------------------------------------------------------

        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # --------------------------------------------------------
        # Django development / ASGI server
        # --------------------------------------------------------

        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # --------------------------------------------------------
        # Django database
        #
        # SQL запросы в production обычно не логируем,
        # поэтому оставляем только ERROR.
        # --------------------------------------------------------

        "django.db.backends": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },

        # --------------------------------------------------------
        # Django security
        # --------------------------------------------------------

        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },

        # --------------------------------------------------------
        # Django migrations
        # --------------------------------------------------------

        "django.db.migrations": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # --------------------------------------------------------
        # Scrapy
        # --------------------------------------------------------

        "scrapy.core.scraper": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },

        # ========================================================
        # YOUR APPLICATIONS
        # ========================================================

        # --------------------------------------------------------
        # Auction
        # --------------------------------------------------------

        "auction": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # --------------------------------------------------------
        # Chat
        # --------------------------------------------------------

        "chat": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # --------------------------------------------------------
        # News
        # --------------------------------------------------------

        "news": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # --------------------------------------------------------
        # Showbill
        # --------------------------------------------------------

        "showbill": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # --------------------------------------------------------
        # General
        # --------------------------------------------------------

        "general": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },

    # ============================================================
    # ROOT LOGGER
    # ============================================================

    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

EMAIL_USE_TLS = True
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_PORT = os.getenv("EMAIL_PORT")
