# Generated by Django 4.0.1 on 2022-03-13 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_mark', models.CharField(choices=[('bmw', 'BMW'), ('merc', 'MERCEDES'), ('toyo', 'TOYOTA')], default='No mark', max_length=100)),
                ('car_model', models.CharField(default='No model', max_length=25)),
                ('engine_type', models.CharField(choices=[('petr', 'Petrol'), ('dies', 'Diesel'), ('hyb', 'Hybrid'), ('elec', 'Electro')], default='No type', max_length=100)),
                ('engine_capacity', models.IntegerField(default='No capacity')),
                ('drive', models.CharField(choices=[('fwd', 'Front-wheel drive'), ('rwd', 'Rear-wheel drive'), ('awd', 'Automatic 4WD'), ('4wd', 'Full-time 4WD')], default='No type', max_length=100)),
                ('gear_box', models.CharField(choices=[('auto', 'Automatic'), ('man', 'Manual')], default='No type', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('win', models.CharField(blank=True, max_length=17, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
