# Generated by Django 4.0.1 on 2022-03-17 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showbill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_adverts', to=settings.AUTH_USER_MODEL),
        ),
    ]
