# Generated by Django 4.0.1 on 2022-03-14 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showbill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gear_box',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_usd',
        ),
        migrations.RemoveField(
            model_name='car',
            name='win',
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showbill.carmark'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showbill.carmodel'),
        ),
    ]
