# Generated by Django 4.0.1 on 2022-03-14 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showbill', '0002_remove_car_description_remove_car_drive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
