# Generated by Django 4.0.1 on 2026-09-21 12:19

from django.db import migrations


def copy_advert_images(apps, schema_editor):
    Advert = apps.get_model('showbill', 'Advert')
    AdvertImage = apps.get_model('showbill', 'AdvertImage')
    for advert in Advert.objects.all():
        if advert.image:
            AdvertImage.objects.create(advert_id=advert.id, image=advert.image)


class Migration(migrations.Migration):

    dependencies = [
        ('showbill', '0002_advertimage'),
    ]

    operations = [
        migrations.RunPython(copy_advert_images, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='advert',
            name='image',
        ),
    ]
