# Generated by Django 4.0.1 on 2026-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showbill', '0003_remove_advert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, default='No capacity', max_digits=5),
        ),
    ]
