# Generated by Django 4.0.1 on 2022-03-14 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showbill', '0003_alter_car_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmarks', to='showbill.carmark'),
        ),
    ]
