# Generated by Django 4.0.1 on 2026-09-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showbill', '0004_alter_advert_engine_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='advert',
            name='win',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
    ]
