# Generated by Django 4.0.1 on 2022-03-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showbill', '0007_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='showbill.carmark'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='showbill.carmodel'),
        ),
    ]
