# Generated by Django 4.0.1 on 2022-03-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showbill', '0009_alter_car_mark_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodels', to='showbill.carmark'),
        ),
    ]
